### PR TITLE
Native notifications on Linux without libnotify

### LINKED ISSUE #1026: Telegram comes to focus when clicking notifications from other applications
I actually don't know if this is Telegram or KDE **bug**, but when Telegram is launched and minimized to tray and a new e-mail arrives triggering a "New mail notification" and you push "Show mail" button -> Telegram desktop app is maximized. The same is when you get a download finished in FireFox and receive a notification with a button "Open" (to open a folder with the downloaded file). 
Push the button and for some reason Telegram app is maximized. I use gentoo. Telegram app is simply downloaded from its web-site.

So, **steps to reproduce** (always for me):
1. configure KDE notifications so that they have some buttons to push, e.g. "Show mail" for KMail.
2. Start Telegram and minimize it to tray.
3. Receive a button-containing-notification
4. Push a button in it.

**Expected result**: Show a KMail with new message.
**Actual result**: Telegram is maximized and focused. The new message is opened in a background.
**Reproduces** always.

I attach a screenshot with an example of the notifications and buttons.

telegram-send

### PR DESCRIPTION
**Pull request by ilya-fedin**
This change removes the need of gtk for native notifications on Linux
Closes #1026

### CODE REVIEW

**Comment by ilya-fedin** [comment]
Added possible fix for #1026 and (duplicate) #6507 
But I have no idea for which notification daemon there was a hack that caused this problem

**Comment by Aokromes** [comment]
@ilya-fedin edit 1st post and add a note "closes #1026" plz :)

**Comment by ilya-fedin** [comment]
@Aokromes ok

**Comment by ilya-fedin** [comment]
:thinking: travis-ci failed with -Werror=enum-compare

```
/home/travis/build/telegramdesktop/tdesktop/upstream/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp: In member function ‘QStringList Platform::Notifications::NotificationData::getServerInformation()’:

/home/travis/build/telegramdesktop/tdesktop/upstream/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp:90:67: error: comparison between ‘enum QVariant::Type’ and ‘enum QMetaType::Type’ [-Werror=enum-compare]

    if (serverInformationReply.arguments()[i].type() == QMetaType::QString) {
```

But Qt documentation recommends comparsion with QMetaType https://doc.qt.io/QT-5/qvariant.html#type

Should I add -Wno-enum-compare to build scripts?

**Comment by 23rd** [comment]
> Should I add -Wno-enum-compare to build scripts?

You can just replace `type()` with `userType()`.
So it will be:
```
if (serverInformationReply.arguments()[i].userType() == QMetaType::QString) {
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 1]
```diff
@@ -7,390 +7,264 @@ For license and copyright information please follow this link:
...
-	NotificationData(const std::shared_ptr<Manager*> &guarded, const QString &title, const QString &body, const QStringList &capabilities, PeerId peerId, MsgId msgId)
-	: _data(Libs::notify_notification_new(title.toUtf8().constData(), body.toUtf8().constData(), nullptr)) {
-		if (valid()) {
-			init(guarded, capabilities, peerId, msgId);
-		}
-	}
-	bool valid() const {
-		return (_data != nullptr);
+	if(!_serverInformation.isEmpty()) {
+		_specificationVersion = parseSpecificationVersion();
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: According to this place, we don't really need to keep `_serverInformation`.
This list of strings is used only for parsing of specification version, so it can be passed to the method as a single argument.
Something like this.
```
_specificationVersion = parseSpecificationVersion(getServerInformation());
```
And then.
```
QVersionNumber NotificationData::parseSpecificationVersion(QStringList information) {
	if (information.size() >= 4) {
		return QVersionNumber::fromString(information[3]);
	} else {
		LOG(("Native notification error: server information should have 4 elements"));
	}

	return QVersionNumber();
}
```
As a result, we can safely remove `_serverInformation`.

(By the way, the current code style prefers the `std::vector<QString>` over the `QStringList`.

Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Fixed :ok_hand:

**Comment by ilya-fedin** [comment]
I remembered that this PR also fixes #3750, because now there is no call to GetServerName in Supported(), instead the interface is checked for validity. I don’t know if I need to add this to the first post, because issue is auto-closed.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 2]
```diff
@@ -7,390 +7,274 @@ For license and copyright information please follow this link:
...
 	}
 
-	~NotificationData() {
-		if (valid()) {
-//			if (_handlerId > 0) {
-//				Libs::g_signal_handler_disconnect(Libs::g_object_cast(_data), _handlerId);
-//			}
-//			Libs::notify_notification_clear_actions(_data);
-			Libs::g_object_unref(Libs::g_object_cast(_data));
+	if (std::find(capabilities.begin(), capabilities.end(), qsl("body-markup")) != capabilities.end()) {
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: All such lines can be replaced with the range-v3.
Something like this.
```
if (ranges::find(capabilities, qsl("body-markup")) != capabilities.end()) {
```
Also to shorten the code we can move the `capabilities.end()` to a new variable. For example.
```
const auto endCap = end(capabilities);
if (ranges::find(capabilities, qsl("body-markup")) != endCap) {
...
if (ranges::find(capabilities, qsl("actions")) != endCap) {
...
etc
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 3]
```diff
@@ -7,390 +7,274 @@ For license and copyright information please follow this link:
...
+			}
+			copyFrom = i + 1;
+		}
+	}
+	if (copyFrom > 0) {
+		result.append(data + copyFrom, textSize - copyFrom);
+		return result;
+	}
+	return text;
+}
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: I'm not sure, but why we can't just use [toHtmlEscaped()](https://doc.qt.io/qt-5/qstring.html#toHtmlEscaped)?

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 4]
```diff
@@ -7,390 +7,274 @@ For license and copyright information please follow this link:
...
-//				Libs::g_signal_handler_disconnect(Libs::g_object_cast(_data), _handlerId);
-//			}
-//			Libs::notify_notification_clear_actions(_data);
-			Libs::g_object_unref(Libs::g_object_cast(_data));
+	if (std::find(capabilities.begin(), capabilities.end(), qsl("body-markup")) != capabilities.end()) {
+		if (!subtitle.isEmpty()) {
+			_body = qstr("<b>") + escapeHtml(subtitle) + qstr("</b>") + '\n' + escapeHtml(msg);
+		} else {
+			_body = escapeHtml(msg);
+		}
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: This can be simplified.
```
_body = subtitle.isEmpty()
	? escapeHtml(msg)
	: QString("<b>%1</b>\n%2")
		.arg(escapeHtml(subtitle))
		.arg(escapeHtml(msg));
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 5]
```diff
@@ -7,390 +7,274 @@ For license and copyright information please follow this link:
...
+}
 
-	bool hasPoorSupport() const {
-		return _poorSupported;
-	}
-	bool hasActionsSupport() const {
-		return _actionsSupported;
-	}
+bool NotificationData::show() {
+	QStringList actionsStringList(QList<QString>::fromVector(QVector<QString>::fromStdVector(_actions)));
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Okay, this is insane.
Perhaps I was wrong and it will be better to store `_actions` as `QStringList` in this particular case.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 3 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Hmm, it's code from old implementation

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 2 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 3 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 4 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 5 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 6]
```diff
@@ -7,390 +7,236 @@ For license and copyright information please follow this link:
...
+	QString imageKey;
+
+	if (!_specificationVersion.isNull()) {
+		if (_specificationVersion.majorVersion() == 1 && _specificationVersion.minorVersion() >= 2 || _specificationVersion.majorVersion() > 1) {
+			imageKey = "image-data";
+		} else if (_specificationVersion.majorVersion() == 1 && _specificationVersion.minorVersion() == 1) {
+			imageKey = "image_data";
+		} else if (_specificationVersion.majorVersion() == 1 && _specificationVersion.minorVersion() < 1 || _specificationVersion.majorVersion() < 1) {
+			imageKey = "icon_data";
+		} else {
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: 1.
These huge conditions can be easily shortened with a new variables.
```
const auto major = _specificationVersion.majorVersion();
const auto minor = _specificationVersion.minorVersion();
if (major == 1 && minor >= 2) {
...
```

2.
It would be better to have a clearly `if ((a && b) || c)` condition instead of unclearly `if (a && b || c)`.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 7]
```diff
@@ -7,390 +7,236 @@ For license and copyright information please follow this link:
...
-		LOG(("LibNotify Error: could not get server name!"));
-		return QString();
-	}
-	if (!name) {
-		LOG(("LibNotify Error: successfully got empty server name!"));
-		return QString();
+	if (serverInformationReply.type() == QDBusMessage::ReplyMessage) {
+		for (int i = 0; i < serverInformationReply.arguments().size(); ++i) {
+			if (static_cast<QMetaType::Type>(serverInformationReply.arguments()[i].type()) == QMetaType::QString) {
+				serverInformation.push_back(serverInformationReply.arguments()[i].toString());
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Can be simplified with the `for ( a : b )` loop.
For example.
```
for (const auto &arg : serverInformationReply.arguments()) {
	if (static_cast<QMetaType::Type>(arg.type()) == QMetaType::QString) {
		serverInformation.push_back(arg.toString());
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 8]
```diff
@@ -7,390 +7,236 @@ For license and copyright information please follow this link:
...
-		}
-	}
-	if (copyFrom > 0) {
-		result.append(data + copyFrom, textSize - copyFrom);
-		return result;
-	}
-	return text;
-}
+NotificationData::NotificationData(const std::shared_ptr<Manager*> &guarded, const QString &title, const QString &subtitle, const QString &msg, PeerId peerId, MsgId msgId)
+: _notificationInterface("org.freedesktop.Notifications", "/org/freedesktop/Notifications", "org.freedesktop.Notifications")
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: I would suggest you to move the repeated constant values to the separate constants.
Something like this.
```
namespace {

const auto kService = QString("org.freedesktop.Notifications");
const auto kPath = QString("/org/freedesktop/Notifications");

} // namespace
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 6 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 7 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 8 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 9]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
-			GError *error = nullptr;
-			Libs::notify_notification_close(_data, &error);
-			if (!error) {
-				return true;
+	if (!capabilities.empty()) {
+		QString capabilitiesString;
+
+		for (const auto &capability : capabilities) {
+			if (!capabilitiesString.isEmpty()) {
+				capabilitiesString += qstr(", ");
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: This is a useless job for the Release build.

Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Maybe it is better to check is debug logs are enabled than this is a debug build? This should be very helpful if there will be issues with notifications.

Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: > This should be very helpful if there will be issues with notifications.

Well, if this is useful for problems with notifications, we will not get this information from the users, as no one uses the Debug version. I think for a one-time log entry this will be fine to use `LOG()`.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 10]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
 
-	if (auto capabilities = Libs::notify_get_server_caps()) {
-		for (auto capability = capabilities; capability; capability = capability->next) {
-			auto capabilityText = QString::fromUtf8(static_cast<const char*>(capability->data));
-			_capabilities.push_back(capabilityText);
-		}
-		Libs::g_list_free_full(capabilities, g_free);
+const QDBusArgument &operator>>(const QDBusArgument &argument, NotificationData::ImageData &imageData) {
+	argument.beginStructure();
+	argument >> imageData.width >> imageData.height >> imageData.rowStride >> imageData.hasAlpha >> imageData.bitsPerSample >> imageData.channels >> imageData.data;;
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]:
```suggestion
	argument >> imageData.width >> imageData.height >> imageData.rowStride >> imageData.hasAlpha >> imageData.bitsPerSample >> imageData.channels >> imageData.data;
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 11]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
 
-	struct QueuedNotification {
-		PeerData *peer = nullptr;
-		MsgId msgId = 0;
-		QString title;
-		QString body;
-		bool hideNameAndPhoto = false;
-	};
+	if (capabilitiesReply.isValid()) {
+		return capabilitiesReply.value().toVector().toStdVector();
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: In my opinion, we can remove the blank elements from the vector right away.

```suggestion
		auto capabilities = capabilitiesReply.value();
		capabilities.removeAll(QString());
		return capabilities | ranges::to_vector;
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 12]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
+		QString capabilitiesString;
+
+		for (const auto &capability : capabilities) {
+			if (!capabilitiesString.isEmpty()) {
+				capabilitiesString += qstr(", ");
 			}
 
-			logError(error);
+			capabilitiesString += capability;
 		}
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: This loop can be replaced with `std::accumulate`.
For example.
```
const auto capabilitiesString = std::accumulate(
	capabilities.begin(),
	capabilities.end(),
	QString{},
	[](auto &s, auto &p) { return s += (p + qstr(", ")); }).chopped(2);
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 8 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Moving such consts into an anonymous namespace is welcome.
An example from the project code.
https://github.com/telegramdesktop/tdesktop/blob/0c0c8f3584b500ef053bb1a4d9165cdbd9e18394/Telegram/SourceFiles/window/themes/window_theme.cpp#L36-L42

**Comment by 23rd** [comment]
By the way, all new project files follow the style with the column limit of 78.
It's quite difficult to work with long lines. =(
So, I think it would be great to split up them.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 13]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
-		}
-		if (_capabilities.contains(qsl("body-markup"))) {
-			_markupSupported = true;
-		}
-	} else {
-		LOG(("LibNotify Error: could not get capabilities!"));
+auto NotificationDaemonRunning = false;
+bool Supported() {
+	static auto Checked = false;
+	if (!Checked) {
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: What is the reason to keep the naked `NotificationDaemonRunning` variable here? You can move it to the `Supported()` like you did with the `static auto Checked`.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 14]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
+	if (serverInformation.size() >= 4) {
+		return QVersionNumber::fromString(serverInformation[3]);
+	} else {
+		LOG(("Native notification error: server information should have 4 elements"));
+	}
 
-	using Notifications = QMap<PeerId, QMap<MsgId, Notification>>;
-	Notifications _notifications;
+	return QVersionNumber();
+}
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Nitpick: There is no reason to keep this function as a class method and it can be safely moved to anonymous namespace.
```
namespace {

auto ParseSpecificationVersion(const std::vector<QString> &serverInformation) {
	if (serverInformation.size() >= 4) {
		return QVersionNumber::fromString(serverInformation[3]);
	} else {
		LOG(("Native notification error: server information should have 4 elements"));
	}

	return QVersionNumber();
}

} // namespace
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp [hunk 15]
```diff
@@ -7,390 +7,244 @@ For license and copyright information please follow this link:
...
-	}
-#endif // !TDESKTOP_DISABLE_GTK_INTEGRATION
-	return nullptr;
-}
+void NotificationData::setImage(const QString &imagePath) {
+	QString imageKey;
+
+	if (!_specificationVersion.isNull()) {
+		const auto majorVersion = _specificationVersion.majorVersion();
+		const auto minorVersion = _specificationVersion.majorVersion();
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]:
```suggestion
		const auto minorVersion = _specificationVersion.minorVersion();
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 13 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: As far as I understand, the point here is that the check is performed only once - at startup.
`static auto Checked` was in `Supported()` already: https://github.com/telegramdesktop/tdesktop/blob/0c0c8f3584b500ef053bb1a4d9165cdbd9e18394/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L267
Windows version has similar code: https://github.com/telegramdesktop/tdesktop/blob/0c713a930a40900c979205d60521532a2e67377d/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L306-L312

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.h [hunk 16]
```diff
@@ -23,16 +28,62 @@ inline bool SkipToast() {
 inline void FlashBounce() {
 }
 
-void Finish();
+class NotificationData : public QObject {
+	Q_OBJECT
```
Comment (23rd) [inline Telegram/SourceFiles/platform/linux/notifications_manager_linux.h]: I think we can safely remove `Q_OBJECT` to avoid an unnecessary extra MOC. 
```suggestion
```

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 11 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Which blank elements? o_O

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.h (hunk 16 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.h]: No, we can't
https://github.com/telegramdesktop/tdesktop/blob/3a0c597682890ab15b3b2c61a02adf09093c989f/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L66
https://github.com/telegramdesktop/tdesktop/blob/3a0c597682890ab15b3b2c61a02adf09093c989f/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L90

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 11 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: You have the following lines in your code.

https://github.com/telegramdesktop/tdesktop/blob/3a0c597682890ab15b3b2c61a02adf09093c989f/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L43-L45

So you are probably assuming that there may be blank elements?

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.h (hunk 16 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.h]: Did you try?

Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.h]: Yes, I added Q_OBJECT only after a lot of tries without it

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 13 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Yes, and you can see that these variables are at least in the anonymous namespace.

https://github.com/telegramdesktop/tdesktop/blob/0c713a930a40900c979205d60521532a2e67377d/Telegram/SourceFiles/platform/win/notifications_manager_win.cpp#L296-L313

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 11 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: No, it is a list of daemon capabilities for debug purposes.
It is also a port of https://github.com/telegramdesktop/tdesktop/blob/0c0c8f3584b500ef053bb1a4d9165cdbd9e18394/Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp#L371

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 13 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Okay, I'll put it in an anonymous namespace

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 11 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: Oops, I misread the condition, sorry.

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.h (hunk 16 above)
Comment (23rd) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.h]: Okay.

**Comment by 23rd** [comment]
Hmm, do we really need to create the `QDBusInterface` in each new `NotificationData`? Can we create a single interface and use it for all future notifications? Can the provided information be changed during the tdesktop execution?

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 8 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 9 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 10 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 12 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 13 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 14 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

File: Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp (hunk 15 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/linux/notifications_manager_linux.cpp]: fixed

**Comment by ilya-fedin** [comment]
> By the way, all new project files follow the style with the column limit of 78.
> It's quite difficult to work with long lines. =(
> So, I think it would be great to split up them.
> (Except for comments with links.)

fixed

> Hmm, do we really need to create the `QDBusInterface` in each new `NotificationData`? Can we create a single interface and use it for all future notifications? Can the provided information be changed during the tdesktop execution?

I checked - it works without that. But it is still necessary to request capabilities and specification version every time, because user can replace notification daemon (or it can be replaced by system upgrade, because notification daemon doesn't works all the time and only starts upon notification request by dbus activation).

**Comment by john-preston** [comment]
Thanks a lot!
