### PR TITLE
Open map in browser if default "bingmaps:" handler is not found

### LINKED ISSUE #3571: If Bing Maps isn't installed, open shared location in browser
### Steps to reproduce
1. Use Windows 10 and don't have Bing Maps ("Maps" in menu) installed
2. Click a shared location

### Expected behaviour
If no Bing Maps installed, open Google Maps in default browser (like on Linux)

### Actual behaviour
image

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.1.7

**Used theme**: Default

### PR DESCRIPTION
**Pull request by Hermesiss**
Fixes #3571 

If you want to test locally but don't want to uninstall maps - just change "bingmaps" to something unexisting in line 559

### CODE REVIEW

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 1]
```diff
@@ -546,5 +547,20 @@ void psSendToMenu(bool send, bool silent) {
 }
 
 bool psLaunchMaps(const Data::LocationPoint &point) {
+	IApplicationAssociationRegistration* aar;
```
Comment (john-preston) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:550]: Please zero initialize (in this case to `nullptr`) variables so that at no moment there are variables with uninitialized memory.

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 2]
```diff
@@ -546,5 +547,20 @@ void psSendToMenu(bool send, bool silent) {
...
+
+	const auto hr = CoCreateInstance(CLSID_ApplicationAssociationRegistration,
+	                                 nullptr, CLSCTX_INPROC,
+	                                 __uuidof(IApplicationAssociationRegistration),
+	                                 reinterpret_cast<void**>(&aar));
+
+	if (SUCCEEDED(hr)) {
+		LPWSTR current_app;
```
Comment (john-preston) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:558]: The same, please initialize either to `nullptr` or to an empty string literal.

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 3]
```diff
@@ -546,5 +547,20 @@ void psSendToMenu(bool send, bool silent) {
 }
 
 bool psLaunchMaps(const Data::LocationPoint &point) {
+	IApplicationAssociationRegistration* aar;
+
+	const auto hr = CoCreateInstance(CLSID_ApplicationAssociationRegistration,
+	                                 nullptr, CLSCTX_INPROC,
+	                                 __uuidof(IApplicationAssociationRegistration),
+	                                 reinterpret_cast<void**>(&aar));
```
Comment (john-preston) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:555]: In case of long parameters we try to stick to that style in the rest of the codebase:
```
const auto hr = CoCreateInstance(
[tab]arg1,
[tab]arg2,
[tab]arg3,
...);
```

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 4]
```diff
@@ -546,5 +547,20 @@ void psSendToMenu(bool send, bool silent) {
...
+
+	if (SUCCEEDED(hr)) {
+		LPWSTR current_app;
+		const auto result = aar->QueryCurrentDefault(L"bingmaps", AT_URLPROTOCOL, AL_EFFECTIVE, &current_app);
+
+		if (FAILED(result))
```
Comment (john-preston) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:561]: Even single-line `if` blocks are wrapped with `{ .. }`.

**Review by john-preston — CHANGES_REQUESTED** [review]
Thanks, this is a really important fix. I'd like to ask for several small changes.

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 5]
```diff
@@ -546,5 +547,27 @@ void psSendToMenu(bool send, bool silent) {
 }
 
 bool psLaunchMaps(const Data::LocationPoint &point) {
+	IApplicationAssociationRegistration* aar = nullptr;
```
Comment (23rd) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:550]:
```suggestion
	IApplicationAssociationRegistration *aar = nullptr;
```

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 6]
```diff
@@ -546,5 +547,27 @@ void psSendToMenu(bool send, bool silent) {
...
+	IApplicationAssociationRegistration *aar = nullptr;
+
+	const auto hr = CoCreateInstance(
+		CLSID_ApplicationAssociationRegistration,
+		nullptr,
+		CLSCTX_INPROC,
+		__uuidof(IApplicationAssociationRegistration),
+		reinterpret_cast<void**>(&aar));
+
+	if (SUCCEEDED(hr)) {
```
Comment (23rd) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:559]: I'm not really sure, but perhaps it makes sense to add an additional check for `nullptr`?
```suggestion
	if (SUCCEEDED(hr) && aar) {
```

Comment (Hermesiss) [reply Telegram/SourceFiles/platform/win/specific_win.cpp:559]: I think aar can never be `nullptr` if hr succeeded, but better safe than sorry

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 7]
```diff
@@ -546,5 +547,27 @@ void psSendToMenu(bool send, bool silent) {
...
+	IApplicationAssociationRegistration *aar = nullptr;
+
+	const auto hr = CoCreateInstance(
+		CLSID_ApplicationAssociationRegistration,
+		nullptr,
+		CLSCTX_INPROC,
+		__uuidof(IApplicationAssociationRegistration),
+		reinterpret_cast<void**>(&aar));
+
+	if (SUCCEEDED(hr && aar)) {
```
Comment (ilya-fedin) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:559]: I guess that breaks the check for SUCCEEDED since hr transforms into 1 or 0...

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 8]
```diff
@@ -546,5 +547,27 @@ void psSendToMenu(bool send, bool silent) {
 }
 
 bool psLaunchMaps(const Data::LocationPoint &point) {
+	IApplicationAssociationRegistration *aar = nullptr;
```
Comment (ilya-fedin) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:550]: Shouldn't it uses ComPtr like the rest of the codebase? :thinking:

File: Telegram/SourceFiles/platform/win/specific_win.cpp (hunk 6 above)
Comment (ilya-fedin) [reply Telegram/SourceFiles/platform/win/specific_win.cpp]: btw, there doesn't seem to be such checks in the rest of the codebase, e.g.
https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/SourceFiles/platform/win/windows_app_user_model_id.cpp#L170-L172

File: Telegram/SourceFiles/platform/win/specific_win.cpp [hunk 9]
```diff
@@ -546,5 +547,27 @@ void psSendToMenu(bool send, bool silent) {
...
+
+	const auto hr = CoCreateInstance(
+		CLSID_ApplicationAssociationRegistration,
+		nullptr,
+		CLSCTX_INPROC,
+		__uuidof(IApplicationAssociationRegistration),
```
Comment (ilya-fedin) [inline Telegram/SourceFiles/platform/win/specific_win.cpp:556]: Doesn't `IID_IApplicationAssociationRegistration` exist? :thinking:

**Comment by john-preston** [comment]
Ok, thanks. I'll rewrite it to C++/WinRT helpers.

**Comment by Hermesiss** [comment]
Thanks! Don't forget to fix `if (success...` line!
