### PR TITLE
Fix building against ffmpeg-4.x

### LINKED ISSUE #28660: Build failure with ffmpeg-4.x
### Steps to reproduce

Build with ffmpeg-4.x.

### Expected behaviour

Successful build.

### Actual behaviour

```
[443/1490] /usr/bin/x86_64-pc-linux-gnu-g++ -DCRL_FORCE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DGI_INLINE -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DKCOREADDONS_EXPORT="" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x051500 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_base -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_rpl -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_crl -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_ui -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_ui/emoji_suggestions -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtCore/6.7.3 -isystem /usr/include/qt6/QtCore/6.7.3/QtCore -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtGui/6.7.3 -isystem /usr/include/qt6/QtGui/6.7.3/QtGui -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtWidgets/6.7.3 -isystem /usr/include/qt6/QtWidgets/6.7.3/QtWidgets -isystem /usr/include/qt6/QtOpenGLWidgets -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtSvg -isystem /usr/include/qt6/QtDBus -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/expected/include -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/kcoreaddons/src/lib/io -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/kcoreaddons/src/lib/util -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/cmake/external/kcoreaddons/headers/public -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/Telegram/lib_base/gen -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/gen -isystem /usr/include/cppgir -isystem /usr/include/cppgir/gi -isystem /usr/include/cppgir/override -isystem /usr/include/gio-unix-2.0 -isystem /usr/lib64/libffi/include -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/Telegram/lib_ui/gen  -DNDEBUG -march=native -O2 -pipe -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -fuse-ld=mold -std=gnu++20 -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -pthread -MD -MT Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o -MF Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o.d -o Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o -c /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
FAILED: Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DCRL_FORCE_COMMON_QUEUE -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION -DGI_INLINE -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_56 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_56 -DKCOREADDONS_EXPORT="" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x051500 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_DEBUG -DQT_NO_KEYWORDS -DQT_OPENGLWIDGETS_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_base -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_rpl -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_crl -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_ui -I/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/lib_ui/emoji_suggestions -isystem /usr/include/qt6/QtCore -isystem /usr/include/qt6 -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtCore/6.7.3 -isystem /usr/include/qt6/QtCore/6.7.3/QtCore -isystem /usr/include/qt6/QtGui -isystem /usr/include/qt6/QtGui/6.7.3 -isystem /usr/include/qt6/QtGui/6.7.3/QtGui -isystem /usr/include/qt6/QtOpenGL -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6/QtWidgets/6.7.3 -isystem /usr/include/qt6/QtWidgets/6.7.3/QtWidgets -isystem /usr/include/qt6/QtOpenGLWidgets -isystem /usr/include/qt6/QtNetwork -isystem /usr/include/qt6/QtSvg -isystem /usr/include/qt6/QtDBus -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/expected/include -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/kcoreaddons/src/lib/io -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/ThirdParty/kcoreaddons/src/lib/util -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/cmake/external/kcoreaddons/headers/public -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/Telegram/lib_base/gen -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/gen -isystem /usr/include/cppgir -isystem /usr/include/cppgir/gi -isystem /usr/include/cppgir/override -isystem /usr/include/gio-unix-2.0 -isystem /usr/lib64/libffi/include -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full_build/Telegram/lib_ui/gen  -DNDEBUG -march=native -O2 -pipe -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -fuse-ld=mold -std=gnu++20 -fPIC -fno-strict-aliasing -pipe -Wall -Wextra -Wno-unused-parameter -Wno-switch -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-sign-compare -Wno-deprecated -pthread -MD -MT Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o -MF Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o.d -o Telegram/CMakeFiles/lib_ffmpeg.dir/SourceFiles/ffmpeg/ffmpeg_utility.cpp.o -c /var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp
/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp: In function ‘FFmpeg::SwresamplePointer FFmpeg::MakeSwresamplePointer(uint64_t, AVSampleFormat, int, uint64_t, AVSampleFormat, int, SwresamplePointer*)’:
/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp:567:37: error: request for member ‘get’ in ‘existing’, which is of pointer type ‘FFmpeg::SwresamplePointer*’ {aka ‘std::unique_ptr<SwrContext, FFmpeg::SwresampleDeleter>*’} (maybe you meant to use ‘->’ ?)
  567 |                 existing ? existing.get() : nullptr,
      |                                     ^~~
/var/tmp/portage/net-im/telegram-desktop-5.7.2/work/tdesktop-5.7.2-full/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp:581:9: error: ‘error’ was not declared in this scope; did you mean ‘perror’?
  581 |         error = AvErrorWrap(swr_init(result));
      |         ^~~~~
      |         perror
```
See https://bugs.gentoo.org/942770 for detailed info.

### Operating system

Gentoo

### Version of Telegram Desktop

5.7.2

### Installation source

Other (unofficial) source

### Crash ID

_No response_

### Logs

```shell
https://bugs.gentoo.org/942770
```

### PR DESCRIPTION
**Pull request by jovaska1337**
Tested against ffmpeg 4.4.5 and 6.1.2 though there may be versions in between where this breaks. Fixes #28660.

### CODE REVIEW

File: Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp [hunk 1]
```diff
@@ -576,6 +576,7 @@ SwresamplePointer MakeSwresamplePointer(
 	if (!result) {
 		LogError(u"swr_alloc_set_opts"_q);
 	}
+	auto
```
Comment (ilya-fedin) [inline Telegram/SourceFiles/ffmpeg/ffmpeg_utility.cpp:579]: Looks fragile... Wouldn't having `AvErrorWrap error;` before ifndef block be better?

File: Telegram/SourceFiles/media/audio/media_audio_local_cache.cpp [hunk 2]
```diff
@@ -44,7 +44,13 @@ constexpr auto kFrameSize = 4096;
 		return {};
 	}
 
+
+#if DA_FFMPEG_NEW_CHANNEL_LAYOUT
```
Comment (ilya-fedin) [inline Telegram/SourceFiles/media/audio/media_audio_local_cache.cpp:48]: This isn't correct. This macro is checking for libavutil version to be higher than 57.28.100. av_find_best_stream belongs to libavformat and has changed to the const pointer in 58.79.100 as far as I can see by ffmpeg commit history.

Comment (ilya-fedin) [reply Telegram/SourceFiles/media/audio/media_audio_local_cache.cpp:48]: i.e.
```suggestion
#if LIBAVFORMAT_VERSION_INT >= AV_VERSION_INT(58, 79, 100)
```

**Comment by jovaska1337** [comment]
I have made the changes you suggested.

**Comment by ilya-fedin** [comment]
Thanks but there's no need to have a separate commit... Can you squash it?

**Comment by jovaska1337** [comment]
Ok, it is now squashed into a single commit.

**Comment by ilya-fedin** [comment]
Thanks!

**Comment by john-preston** [comment]
Thanks!
