### PR TITLE
[Regression] Bring back original video quality option, handle attributes correctly

### LINKED ISSUE #29780: No original video quality option in the video player dropdown
### Steps to reproduce

1. Open a [**processed**](https://t.me/durov/448) video that has multiple quality options
2. Click the gear button

### Expected behaviour

There should be an option to select the **Original** video quality (like on Android)
Image

### Actual behaviour

There's no **Original** video quality option, only transcoded garbage 🤨
Image

P.S. There should be 2 separate menus for quality/speed. The current implementation, where speed options are replaced with quality options when !_qualities.empty(), makes absolutely no sense.

### Operating system

Windows 11

### Version of Telegram Desktop

6.1.3 x64

### Installation source

Static binary from official website

### Crash ID

_No response_

### Logs

```shell

```

### LINKED ISSUE #30407: Video player follows incorrect attributes for scaling, duration
### Steps to reproduce

Open a video with
1. quality options
2. Incorrect w, h or/and duration attributes

Examples:
- https://t.me/Ateobreaking/165411 (1280x720 uploaded as fake 848x464, iOS client)
- https://t.me/cursedvideofiles/6 (same video id as above, just added some useful context)
- https://t.me/cursedvideofiles/8 (video from above reuploaded as fake 100x100, fake duration of 1 sec)
- https://t.me/cursedvideofiles/7 (video from above reuploaded as fake 1488x1488, fake duration of 1488 sec)
- https://t.me/warhistoryalconafter/261089 (1280x720 uploaded as fake 848x464, iOS client)
- https://t.me/strikedronescompany/418 (1920x1080 uploaded as fake 848x464, iOS client)

0:08 Note how the dimensions of the video player change from **1280x720** => **incorrect 848x464**, even thought the selected **480p** stream is supposed to have the resolution of **852x480**

https://github.com/user-attachments/assets/e260abde-e927-475d-91ef-621402097026

### Expected behaviour

The video player loads attributes for the selected stream and doesn't follow them blindly. This results in correct video player dimensions, duration being displayed.

### Actual behaviour

The video player blindly relies on wrong **original file's attributes** instead of the attributes of the **steam that's currently selected** in the dropdown menu. This results in wrong video player dimensions, wrong duration being shown.

For dimensions `_document->dimensions` in
https://github.com/telegramdesktop/tdesktop/blob/5f1121123c6cccbb9ed9efa456c211f1c32d7299/Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp#L1180-L1187
For duration `_document->duration()` in
https://github.com/telegramdesktop/tdesktop/blob/5f1121123c6cccbb9ed9efa456c211f1c32d7299/Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp#L4660-L4671

### Operating system

Windows 11

### Version of Telegram Desktop

6.6.2

### Installation source

Static binary from official website

### Crash ID

_No response_

### Logs

```shell

```

### PR DESCRIPTION
**Pull request by comdev1337**
Fixes #29780
Fixes #30407 
Fixes: a bug (?) where the video quality text (SD/HD/4K) is not displayed on the gear button if a video has no `alt_documents` (only speed options are available in the dropdown).

### Summary

This PR aims to help **the minor subset of users with a functioning eyesight** by restoring the original video quality option in the media player. The original stream is included as the second option (consistent with the ordering in the Android client).

[Example video](https://t.me/vkpelmen/3636). Observe: wheels turn into slop when 1080p is selected.

https://github.com/user-attachments/assets/1d32b841-17a8-4f24-9eaa-9a9ba94d0d80

[Example video](https://t.me/cursedvideofiles/9). Handling wrong attributes correctly. We now have a 1080p stream!

https://github.com/user-attachments/assets/25d91513-ed8e-4078-ab73-b404ac26bf82

  ### Implementation
   - Upon resolving video qualities, the original quality is added to the array with a 1000000 integer offset (`Media::kVideoQualityOriginalOffset`). This eliminates resolution ambiguity between an original 1080p stream and a sloppy 1080p.
   - The settings deserializer has been updated to accept values up to 1004320 to ensure the "Original" quality preference persists across restarts.
   - Tie-Breaker Fix: Fixed an edge case in `chooseQuality()` where selecting the transcoded 1080p option selects the original 1080p, if the transcoded stream size is over the original file size, due to
```cpp
if (abs == closestAbs && quality->size < closestSize)
```
   - Get video dimensions from ffmpeg directly (`realsize`), do not rely on attributes whenever possible.
     
  

---
Tried throwing a bunch of different videos at it. Works on my machine.

### CODE REVIEW

File: Telegram/SourceFiles/data/data_document.cpp [hunk 1]
```diff
@@ -611,19 +628,30 @@ not_null<DocumentData*> DocumentData::chooseQuality(
...
-	auto closestAbs = std::abs(height - resolveVideoQuality());
-	auto closestSize = size;
+	if (height >= Media::kVideoQualityOriginalOffset) {
+		return this;
+	}
+	
+	// If a standard quality is requested, try to find the best match among transcoded streams only.
+	DocumentData* closest = nullptr;
+	int closestAbs = -1;
+	int closestSize = -1;
```
Comment (23rd) [inline Telegram/SourceFiles/data/data_document.cpp]: `auto`

Comment (comdev1337) [reply Telegram/SourceFiles/data/data_document.cpp]: updated

File: Telegram/SourceFiles/data/data_document.cpp [hunk 2]
```diff
@@ -611,19 +628,30 @@ not_null<DocumentData*> DocumentData::chooseQuality(
...
+	auto closestAbs = -1;
+	auto closestSize = -1;
+	
 	for (const auto &quality : list) {
+		if (quality == this) {
+			continue; // Skip Original stream for standard quality requests
+		}
 		const auto abs = std::abs(height - quality->resolveVideoQuality());
-		if (abs < closestAbs
+		if (closest == nullptr
```
Comment (23rd) [inline Telegram/SourceFiles/data/data_document.cpp]:
```suggestion
		if (!closest
```

File: Telegram/SourceFiles/media/player/media_player_button.cpp [hunk 3]
```diff
@@ -437,13 +437,17 @@ void SettingsButton::prepareFrame() {
 			: u"%1X"_q.arg(rounded / 10);
 		paintBadge(p, text, RectPart::TopLeft, color);
 	}
-	const auto text = (!_quality)
+	auto displayQuality = _quality;
+	if (displayQuality >= Media::kVideoQualityOriginalOffset) {
+		displayQuality -= Media::kVideoQualityOriginalOffset;
+	}
```
Comment (23rd) [inline Telegram/SourceFiles/media/player/media_player_button.cpp]: Can be `const auto` with `?:`.

File: Telegram/SourceFiles/data/data_document.cpp [hunk 4]
```diff
@@ -578,18 +578,35 @@ void DocumentData::setVideoQualities(
...
 
 int DocumentData::resolveVideoQuality() const {
 	const auto size = isVideoFile() ? dimensions : QSize();
-	return size.isEmpty() ? 0 : std::min(size.width(), size.height());
+	auto result = size.isEmpty() ? 0 : std::min(size.width(), size.height());
+	if (const auto data = video()) {
+		for (const auto &quality : data->qualities) {
+			if (quality != this) {
+				const auto qsize = quality->dimensions;
+				const auto qres = qsize.isEmpty() ? 0 : std::min(qsize.width(), qsize.height());
```
Comment (23rd) [inline Telegram/SourceFiles/data/data_document.cpp]: The ruler of the current code style is 78 chars.

File: Telegram/SourceFiles/media/player/media_player_dropdown.cpp [hunk 5]
```diff
@@ -852,8 +859,12 @@ void SpeedController::fillMenu(not_null<Ui::DropdownMenu*> menu) {
 				: !quality;
 			raw->action()->setEnabled(!chosen);
 			if (!quality) {
+				auto displayHeight = now.height;
+				if (displayHeight >= Media::kVideoQualityOriginalOffset) {
+					displayHeight -= Media::kVideoQualityOriginalOffset;
+				}
```
Comment (23rd) [inline Telegram/SourceFiles/media/player/media_player_dropdown.cpp]: The same.

File: Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp [hunk 6]
```diff
@@ -4770,20 +4773,29 @@ std::vector<int> OverlayWidget::playbackControlsQualities() {
 	auto result = std::vector<int>();
 	result.reserve(list.size());
 	for (const auto &quality : list) {
-		result.push_back(quality->resolveVideoQuality());
+		if (quality == _document) {
+			result.push_back(Media::kVideoQualityOriginalOffset + quality->resolveVideoQuality());
+		} else {
+			result.push_back(quality->resolveVideoQuality());
+		}
```
Comment (23rd) [inline Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp]: `?:`

Comment (comdev1337) [reply Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp]: Replaced with `?:`

File: Telegram/SourceFiles/media/player/media_player_dropdown.cpp (hunk 5 above)
Comment (comdev1337) [reply Telegram/SourceFiles/media/player/media_player_dropdown.cpp]: Updated everything to be <79, replaced with `const auto`, `?:`

File: Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp [hunk 7]
```diff
@@ -4265,8 +4267,22 @@ void OverlayWidget::initStreamingThumbnail() {
...
+			const auto targetDocument = _chosenQuality ? _chosenQuality : _document;
+			if (const auto video = targetDocument->video()) {
+				video->realVideoSize = info.video.realSize;
+			}
+		}
 		applyVideoSize();
 		_streamedQualityChangeFrame = QImage();
+		if (_streamed && _streamed->controls) {
+			const auto weak = base::make_weak(_widget);
+			crl::on_main(weak, [=] {
```
Comment (23rd) [inline Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp]:
```suggestion
			crl::on_main(_widget, [=] {
```
?

File: Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp [hunk 8]
```diff
@@ -4659,12 +4675,16 @@ void OverlayWidget::restartAtSeekPosition(crl::time position) {
 	}
 	const auto overrideDuration = _stories
 		|| (_chosenQuality && _chosenQuality != _document);
+	const auto durationDocument = (_chosenQuality && _chosenQuality != _document)
```
Comment (23rd) [inline Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp:5138]: > _chosenQuality != _document)

Does it really make sense?

File: Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp [hunk 9]
```diff
@@ -4769,21 +4789,30 @@ std::vector<int> OverlayWidget::playbackControlsQualities() {
...
 	auto result = std::vector<int>();
 	result.reserve(list.size());
+	auto seen = std::vector<int>();
 	for (const auto &quality : list) {
-		result.push_back(quality->resolveVideoQuality());
+		const auto res = quality->resolveVideoQuality();
+		const auto value = (quality == _document)
+			? (res + Media::kVideoQualityOriginalOffset)
+			: res;
+		if (std::find(seen.begin(), seen.end(), value) == seen.end()) {
```
Comment (23rd) [inline Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp]:
```suggestion
		if (ranges::find(seen, value) == seen.end()) {
```

Comment (23rd) [reply Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp]: Oh.
Even `ranges::contains`.

File: Telegram/SourceFiles/media/player/media_player_dropdown.cpp [hunk 10]
```diff
@@ -819,7 +819,12 @@ void SpeedController::fillMenu(not_null<Ui::DropdownMenu*> menu) {
 
 	const auto add = [&](int quality) {
 		const auto automatic = tr::lng_mediaview_quality_auto(tr::now);
-		const auto text = quality ? u"%1p"_q.arg(quality) : automatic;
+		const auto offset = Media::kVideoQualityOriginalOffset;
+		const auto text = !quality
+			? automatic
+			: (quality >= offset)
+			? u"Original (%1p)"_q.arg(quality - offset)
```
Comment (23rd) [inline Telegram/SourceFiles/media/player/media_player_dropdown.cpp]: > (quality - offset)

Maybe some std::clamp, idk...

Comment (comdev1337) [reply Telegram/SourceFiles/media/player/media_player_dropdown.cpp]: added clamp up to 4320

File: Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp (hunk 8 above)
Comment (comdev1337) [reply Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp:5138]: This is necessary. We do not want to rely on the provided duration attribute, which might be fake.

See: https://t.me/cursedvideofiles/7

If you open the 720p or 480p stream in 6.6.2, you'll end up with
1) fake duration
2) video player dimensions change according to fake w, h attributes

I aim to resolve these 2 issues:
image

**Comment by comdev1337** [comment]
Made the player more resistant against incorrect width, height, duration attributes. Unfortunately, fake w, h are common.

- The player should now correctly adjust the size per the stream selected.
- The player accounts for weird edge cases (like non-square SAR) when extracting the height for the original doc.

Put some edge cases the current player doesn't account for in https://t.me/cursedvideofiles

Should fix #30407

File: Telegram/SourceFiles/data/data_document.cpp [hunk 11]
```diff
@@ -578,18 +579,65 @@ void DocumentData::setVideoQualities(
...
-				qualities.insert(begin(qualities), this);
+		auto transcodeMax = 0;
+		for (const auto &quality : qualities) {
+			const auto qres = quality->resolveVideoQuality();
+			if (qres > transcodeMax) {
+				transcodeMax = qres;
 			}
 		}
+		const auto apiSize = isVideoFile() ? dimensions : QSize();
+		const auto api = apiSize.isEmpty()
```
Comment (23rd) [inline Telegram/SourceFiles/data/data_document.cpp]: Such names should not be here.

File: Telegram/SourceFiles/media/player/media_player_dropdown.cpp [hunk 12]
```diff
@@ -7,6 +7,7 @@ For license and copyright information please follow this link:
 */
 #include "media/player/media_player_dropdown.h"
 
+#include <algorithm>
```
Comment (23rd) [inline Telegram/SourceFiles/media/player/media_player_dropdown.cpp]:
```suggestion
```

File: Telegram/SourceFiles/media/streaming/media_streaming_player.cpp [hunk 13]
```diff
@@ -62,6 +62,8 @@ void SaveValidVideoInformation(
 
 	SaveValidStateInformation(to.state, std::move(from.state));
 	to.size = from.size;
+	// Propagate physical resolution parsed from the stream
+	to.realSize = from.realSize;
```
Comment (23rd) [inline Telegram/SourceFiles/media/streaming/media_streaming_player.cpp:66]: Physical? 😨

File: Telegram/SourceFiles/media/player/media_player_dropdown.cpp (hunk 12 above)
Comment (comdev1337) [reply Telegram/SourceFiles/media/player/media_player_dropdown.cpp]: removed

File: Telegram/SourceFiles/data/data_document.cpp (hunk 11 above)
Comment (comdev1337) [reply Telegram/SourceFiles/data/data_document.cpp]: replaced these

File: Telegram/SourceFiles/media/streaming/media_streaming_player.cpp (hunk 13 above)
Comment (comdev1337) [reply Telegram/SourceFiles/media/streaming/media_streaming_player.cpp:66]: `Physical` as in the stream resolution as reported by ffmpeg, as opposed to `size` which is adjusted for SAR.
I can rename it to smth like "encoded resolution" if that makes more sense?

**Comment by FishOrBear** [comment]
I tested this PR, and the results are excellent. Previously, the system would generate an AV1-encoded video, which caused the video playback to freeze; now, it utilizes the original video (H.264), thereby preventing the freezing issue.

**Comment by john-preston** [comment]
I'll rewrite it, but thanks.

**Comment by john-preston** [comment]
ah. now conflicts , sorry @comdev1337, fix please

**Comment by comdev1337** [comment]
@john-preston fixed

**Comment by comdev1337** [comment]
@FishOrBear
>Previously, the system would generate an AV1-encoded video, which caused the video playback to freeze; now, it utilizes the original video (H.264)

This may still be an issue if you select a transcoded stream. I believe the client prioritizes fetching av01 over h264 for these.

**Comment by FishOrBear** [comment]
> @FishOrBear
> 
> > Previously, the system would generate an AV1-encoded video, which caused the video playback to freeze; now, it utilizes the original video (H.264)
> 
> This may still be an issue if you select a transcoded stream. I believe the client prioritizes fetching av01 over h264 for these.

Yes, now I just need to select the original video.

It would be helpful to improve the video quality selection button by displaying the video's encoding format and file size; this would make debugging much easier. This is how it works on Telegram for Android.

**Comment by comdev1337** [comment]
> It would be helpful to improve the video quality selection button by displaying the video's encoding format and file size; this would make debugging much easier. This is how it works on Telegram for Android.

The Android client doesn't display the codec, from what I can see
