### PR TITLE
Fix some ffmpeg 7.x related errors

### LINKED ISSUE #28583: compiler errors, invalid conversion, no member named channels
### Steps to reproduce

Try to build `telegram-desktop-git` from AUR on Arch Linux in clean chroot.

### Expected behaviour

Should build without error.  5.6.3 builds successfully.

### Actual behaviour

Build stops at 720/1513.

```
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp: In member function ‘void Ui::RoundVideoRecorder::Private::initEncoding()’:
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:273:17: error: invalid conversion from ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} to ‘int (*)(void*, const uint8_t*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} [-fpermissive]
  273 |                 &Private::Write,
      |                 ^~~~~~~~~~~~~~~
      |                 |
      |                 int (*)(void*, uint8_t*, int) {aka int (*)(void*, unsigned char*, int)}
In file included from /home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:12:
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h:147:14: note:   initializing argument 3 of ‘FFmpeg::FormatPointer FFmpeg::MakeWriteFormatPointer(void*, int (*)(void*, uint8_t*, int), int (*)(void*, const uint8_t*, int), int64_t (*)(void*, int64_t, int), const QByteArray&)’
  147 |         int(*write)(void *opaque, const uint8_t *buffer, int bufferSize),
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp: In member function ‘bool Ui::RoundVideoRecorder::Private::initAudio()’:
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:390:22: error: ‘struct AVCodecContext’ has no member named ‘channels’
  390 |         _audioCodec->channels = _audioCodec->ch_layout.nb_channels;
      |                      ^~~~~~~~
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp: In member function ‘Ui::RoundVideoResult Ui::RoundVideoRecorder::Private::appendToPrevious(Ui::RoundVideoResult)’:
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:517:17: error: invalid conversion from ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} to ‘int (*)(void*, const uint8_t*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} [-fpermissive]
  517 |                 &Private::Write,
      |                 ^~~~~~~~~~~~~~~
      |                 |
      |                 int (*)(void*, uint8_t*, int) {aka int (*)(void*, unsigned char*, int)}
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h:147:14: note:   initializing argument 3 of ‘FFmpeg::FormatPointer FFmpeg::MakeWriteFormatPointer(void*, int (*)(void*, uint8_t*, int), int (*)(void*, const uint8_t*, int), int64_t (*)(void*, int64_t, int), const QByteArray&)’
  147 |         int(*write)(void *opaque, const uint8_t *buffer, int bufferSize),
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp: In member function ‘bool Ui::RoundVideoRecorder::Private::copyPackets(gsl::not_null<AVFormatContext*>, gsl::not_null<AVFormatContext*>, CopyContext&, crl::time)’:
/home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:584:23: warning: ‘void av_init_packet(AVPacket*)’ is deprecated [-Wdeprecated-declarations]
  584 |         av_init_packet(&packet);
      |         ~~~~~~~~~~~~~~^~~~~~~~~
In file included from /usr/include/libavcodec/avcodec.h:44,
                 from /home/builder/build/src/telegram-desktop/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h:19:
/usr/include/libavcodec/packet.h:653:6: note: declared here
  653 | void av_init_packet(AVPacket *pkt);
      |      ^~~~~~~~~~~~~~
```
</details>

### Operating system

Arch Linux

### Version of Telegram Desktop

5.6.4: 78937d716fe6e8fa3b470d378d2fcb54a643f06c

### Installation source

Other (unofficial) source

### Crash ID

_No response_

### Logs

[`telegram-desktop-git.log`](https://github.com/user-attachments/files/17534892/telegram-desktop-git.log)

### PR DESCRIPTION
**Pull request by xiota**
Fixes #28583
Related #28601

### CODE REVIEW

File: Telegram/SourceFiles/ui/controls/round_video_recorder.cpp [hunk 1]
```diff
@@ -107,9 +107,15 @@ class RoundVideoRecorder::Private final {
 		std::array<int64, kMaxStreams> lastDts = { 0 };
 	};
 
+#if DA_FFMPEG_CONST_WRITE_CALLBACK
+	static int Write(void *opaque, const uint8_t *_buf, int buf_size) {
+		uint8_t *buf = const_cast<uint8_t *>(_buf);
```
Comment (dvalter) [inline Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:112]: Maybe it would be better to make the pointer always const here, it should not affect compilation and use with older versions of libav

```patch
diff --git a/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp b/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp
index f01df2165..98af08507 100644
--- a/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp
+++ b/Telegram/SourceFiles/ui/controls/round_video_recorder.cpp
@@ -107,14 +107,14 @@ private:
                std::array<int64, kMaxStreams> lastDts = { 0 };
        };
 
-       static int Write(void *opaque, uint8_t *buf, int buf_size) {
+       static int Write(void *opaque, const uint8_t *buf, int buf_size) {
                return static_cast<Private*>(opaque)->write(buf, buf_size);
        }
        static int64_t Seek(void *opaque, int64_t offset, int whence) {
                return static_cast<Private*>(opaque)->seek(offset, whence);
        }
 
-       int write(uint8_t *buf, int buf_size);
+       int write(const uint8_t *buf, int buf_size);
        int64_t seek(int64_t offset, int whence);
 
        void initEncoding();
@@ -230,7 +230,7 @@ RoundVideoRecorder::Private::~Private() {
        finishEncoding();
 }
 
-int RoundVideoRecorder::Private::write(uint8_t *buf, int buf_size) {
+int RoundVideoRecorder::Private::write(const uint8_t *buf, int buf_size) {
        if (const auto total = _resultOffset + int64(buf_size)) {
                const auto size = int64(_result.size());
                constexpr auto kReserve = 1024 * 1024;
```

Comment (xiota) [reply Telegram/SourceFiles/ui/controls/round_video_recorder.cpp:112]: I tried that.  There were more compiler errors that I didn't want to chase down / figure out how to resolve.

Comment (xiota) [reply Telegram/SourceFiles/ui/controls/round_video_recorder.cpp]: This solution works with ffmpeg 7.0.2.  I must have made a mistake in earlier attempt.  Pushing change to PR.

**Comment by john-preston** [comment]
It looks like it breaks on 6.* then, see the actions.

**Comment by xiota** [comment]
@john-preston Thanks for letting me know.  Force pushed to rebase to 5.7.2 and revert to initial solution.  Test built against ffmpeg 6.1.2 and 7.0.2.

**Comment by john-preston** [comment]
hmm, but the define should somehow flow from ffmpeg version, ideally within this code, so that nothing should be specified outside, like in cmake or elsewhere.

**Comment by xiota** [comment]
The ffmpeg-related defines were added in #27907.  They are already used in multiple files.  I would rather not change them, add duplicate defines, or deviate from precedent.

https://github.com/telegramdesktop/tdesktop/blob/1eeb46d5fcb2bb85eef51f8facb4983e3e55cbc3/Telegram/SourceFiles/ffmpeg/ffmpeg_utility.h#L27-L34

**Comment by john-preston** [comment]
oh, I see, yeah.. thanks
